### ISSUE TITLE
Add `Getting Started` guide to README

### ISSUE THREAD

**Issue by eureka-cpu** [Levitanus/rea-rs#5]
Ref https://github.com/helgoboss/reaper-rs/issues/79#issuecomment-2118602983

**Comment by Levitanus** [comment]
The example from readme should work just fine. I still think, that something with your extension naming or paths.

You can look to the integration test for mac os: https://github.com/Levitanus/rea-rs/blob/main/rea-rs-test/src/integration_test.rs#L155
It runs in CI environment, so works fine.

I'm up to release v0.2.0 with  lot of API updates, and will update readme for it also. But, actually, example from current readme works fine and executes in CI on Linux and Mac

**Comment by Levitanus** [comment]
P.S. The easiest way to check Reaper resource path is from reaper menu: 
![изображение](https://github.com/Levitanus/rea-rs/assets/29713891/cb3da0e1-66de-49e8-9f02-11bda0006121)

The plugin has to be named `reaper_<name>.dylib`

Also check, that crate is of type lib:
```
[lib]
crate-type = ["lib"]
name = "reaper_levitanus"
```

You can check my current extension repository, it is a good example of usage: https://github.com/Levitanus/reaper-levitanus
